name: rollshop
description: "A new Flutter project."


version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core:
  cloud_firestore:
  firebase_storage: 
  firebase_auth: 
  flutter_bloc:
  flutter_screenutil: 
  flutter_image_slideshow:
  flutter_image_compress: 
  flutter_localizations:
    sdk: flutter
  path_provider: 
  get_it:
  shared_preferences:
  image_picker:
  equatable: 
  dartz: 
  conditional_builder_null_safety: 
  internet_connection_checker_plus: 
  cached_network_image: 
  animated_bottom_navigation_bar:
  flutter_native_splash:
  email_validator:
  flutter_svg:
  # adaptive_theme: 
  # persistent_bottom_nav_bar: any


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  flutter_launcher_icons:

# flutter_launcher_icons:
#   android: "launcher_icon"
#   ios: true
#   image_path: "assets/icons/logo.jpeg"
#   min_sdk_android: 21 # android min sdk min:16, default 21
#   web:
#     generate: true
#     image_path: "assets/icons/logo.jpeg"
#     background_color: "#ffffff"
#     theme_color: "#ffffff"
#   windows:
#     generate: true
#     image_path: "assets/icons/logo.jpeg"
#     icon_size: 48 # min:48, max:256, default: 48
#   macos:
#     generate: true
#     image_path: "assets/icons/logo.jpeg"
  


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/svgs/
    - assets/images/chock_types/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
